name: Terraform CI/CD Pipeline

on:
  push:
    branches: [master,develop]
  pull_request:
    branches: [master,develop]

env:
  TF_VERSION: "1.3.0"
  TF_VAR_region: "eu-west-1"

jobs:
  terraform-beta:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        run: cd beta-env && terraform fmt -check -recursive

      - name: Terraform init
        run: cd beta-env && terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ env.TF_VAR_region }}

      - name: Terraform validate
        run: cd beta-env && terraform validate

      - name: Terraform plan
        run: cd beta-env && terraform plan -out=tfplan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ env.TF_VAR_region }}

      - name: Terraform apply
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: terraform apply tfplan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ env.TF_VAR_region }}
  terraform-prod:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: terraform-beta
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: trstringer/manual-approval@v1
        with:
          approvers: boscodalglish

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        run: cd beta-env && terraform fmt -check -recursive

      - name: Terraform init
        run: cd beta-env && terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ env.TF_VAR_region }}

      - name: Terraform validate
        run: cd beta-env && terraform validate

      - name: Terraform plan
        run: cd beta-env && terraform plan -out=tfplan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ env.TF_VAR_region }}

      - name: Terraform apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply tfplan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ env.TF_VAR_region }}